### ISSUE TITLE
Getting TypeError object is not a function when I run browser-sync

### ISSUE THREAD

**Issue by Daniel0524** [shakyShane/gulp-browser-sync#39]
First it happened in my own project, so I tried one of the examples here and it's still happening. Can't figure out the issue and it's really bugging me.

[16:01:26] 'browser-sync' errored after 92 μs
[16:01:26] TypeError: object is not a function

Using sass 3.4.10
Using node v0.10.35

**Comment by shakyShane** [comment]
Please post:

- your full `gulpfile.js`
- browser-sync version.. (find with `npm ls browser-sync`)

**Comment by Daniel0524** [comment]
browser-sync@0.9.1 
and like I said above, I'm using the example in this repo:

https://github.com/shakyShane/gulp-browser-sync/blob/master/gulpfile-example-01.js

**Comment by shakyShane** [comment]
`npm install browser-sync@latest --save-dev` & try again :)

**Comment by Daniel0524** [comment]
Oh weird no idea why I had such an old version, I just started this project a few days ago and my package.json specified latest... Thanks!

**Comment by shakyShane** [comment]
when on 0.x.x you'll never get anything post 1.0.0 automatically
