### ISSUE TITLE
Hard time understanding browserSync.reload

### ISSUE THREAD

**Issue by helpermethod** [shakyShane/gulp-browser-sync#40]
Hi,

I was reading the documentation concerning [Browser Reloading](http://www.browsersync.io/docs/gulp/#gulp-reload) and I am not able to understand the last line of the `default` task

```
gulp.task('default', ['browser-sync'], function () {
    gulp.watch("js/*.js", ['js', browserSync.reload]); // why does this work?
});
```

As far as I know, task dependencies are executed asynchronously, so couldn't the reload happen before the `js` task actually finishes?

**Comment by shakyShane** [comment]
When you return the stream from a previous task (as seen in that example), the next task will not execute until it's finished.
